name: Backport PR to branch
on:
  issue_comment:
    types: [created]
  schedule:
    # once a day at 13:00 UTC to cleanup old runs
    - cron: '0 13 * * *'

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "$GITHUB_REPOSITORY_OWNER"
 
  backport:
    uses: dotnet/arcade/.github/workflows/backport-base.yml@main
    with:
      repository_owners: 'nohwnd,Owners'
